# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\di-msg-send.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(301, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.options_combo = QtWidgets.QComboBox(Dialog)
        self.options_combo.setGeometry(QtCore.QRect(140, 30, 151, 22))
        self.options_combo.setAcceptDrops(True)
        self.options_combo.setEditable(True)
        self.options_combo.setObjectName("options_combo")
        self.options_label = QtWidgets.QLabel(Dialog)
        self.options_label.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.options_label.setObjectName("options_label")
        self.message_edit = QtWidgets.QTextEdit(Dialog)
        self.message_edit.setGeometry(QtCore.QRect(10, 60, 281, 231))
        self.message_edit.setObjectName("message_edit")
        self.send_button = QtWidgets.QPushButton(Dialog)
        self.send_button.setGeometry(QtCore.QRect(10, 300, 281, 28))
        self.send_button.setDefault(True)
        self.send_button.setObjectName("send_button")
        self.pathLabel = QtWidgets.QLabel(Dialog)
        self.pathLabel.setGeometry(QtCore.QRect(10, 340, 91, 16))
        self.pathLabel.setObjectName("pathLabel")
        self.listView = QtWidgets.QLabel(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 360, 281, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setSizeIncrement(QtCore.QSize(0, 3))
        self.listView.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.listView.setText("")
        self.listView.setWordWrap(True)
        self.listView.setObjectName("listView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Send Message"))
        self.options_label.setText(_translate("Dialog", "To:"))
        self.message_edit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.message_edit.setPlaceholderText(_translate("Dialog", "Enter message or drag and drop files here, use ctlr+enter to send message"))
        self.send_button.setText(_translate("Dialog", "Send"))
        self.pathLabel.setText(_translate("Dialog", "Files Attached:"))
